version: '3.8'
services:
  frontend:
    build: .
    container_name: frontend
    ports:
      - "80:3000"
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./public:/usr/share/nginx/html:ro
    networks:
      - webnet

  backend:
    image: nginx:alpine # Placeholder for backend, replace with your backend image
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - webnet

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - webnet

volumes:
  certbot-etc:
  certbot-var:

networks:
  webnet:
    driver: bridge 