# Spring Boot Application Configuration for NEPA Football Broadcast Backend
spring:
  application:
    name: nepa-football-broadcast
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/nepa_football
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  
  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  # Security Configuration
  security:
    user:
      name: admin
      password: admin123
  
  # Jackson Configuration for JSON handling
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api

# JWT Configuration
jwt:
  secret: your-secret-key-here-make-it-long-and-secure-in-production
  expiration: 86400000 # 24 hours in milliseconds

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  info:
    title: NEPA Football Broadcast API
    description: API for NEPA High School Football Broadcasting Platform
    version: 1.0.0
    contact:
      name: NEPA Football Team
      email: info@nepafootball.com

# Logging Configuration
logging:
  level:
    com.nepafootball: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Profile-specific configurations
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/nepa_football_dev
    username: postgres
    password: password

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:nepa_football}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate 